# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MKBDiagnos',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Код МКБ')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('is_finished', models.BooleanField(verbose_name='Является диагнозом')),
                ('level', models.IntegerField(verbose_name='Уровень')),
            ],
            options={
                'verbose_name_plural': 'МКБ',
                'verbose_name': 'МКБ',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OKMUService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='Код ОКМУ')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('is_finished', models.BooleanField(verbose_name='Является услугой')),
                ('level', models.IntegerField(verbose_name='Уровень')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.OKMUService')),
            ],
            options={
                'verbose_name_plural': 'Услуги',
                'verbose_name': 'Услугa',
                'ordering': ['code'],
            },
        ),
    ]
