# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 03:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Системная дата создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Системная дата изменения')),
                ('date', models.DateField(db_index=True, verbose_name='Дата приема')),
                ('additional_data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Дополнительные параметры')),
            ],
            options={
                'verbose_name_plural': 'Назначения',
                'verbose_name': 'Назначение',
            },
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер кабинета')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Кабинеты',
                'verbose_name': 'Кабинет',
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата приема')),
                ('time_start', models.TimeField(verbose_name='Время приема')),
                ('time_end', models.TimeField(verbose_name='Окончание приема')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cabinet', verbose_name='Кабинет')),
                ('performing_services', models.ManyToManyField(to='catalogs.OKMUService', verbose_name='Выполняемые услуги')),
            ],
            options={
                'verbose_name_plural': 'Ячейки',
                'verbose_name': 'Ячейка',
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование мед. учреждения')),
                ('city', models.CharField(max_length=128, verbose_name='Город')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
            ],
            options={
                'verbose_name_plural': 'Мед. учреждения',
                'verbose_name': 'Мед. уреждение',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название подразделения')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Clinic', verbose_name='Мед. учреждение')),
                ('parent_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Department')),
            ],
            options={
                'verbose_name_plural': 'Подразделения',
                'verbose_name': 'Подразделение',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('last_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=128, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('polis_number', models.CharField(max_length=16, verbose_name='Номер полиса')),
            ],
            options={
                'verbose_name_plural': 'Пациенты',
                'verbose_name': 'Пациент',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=128, verbose_name='Полное имя')),
                ('specialization', models.CharField(blank=True, max_length=128, null=True, verbose_name='Специализация')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Department', verbose_name='Подразделение')),
                ('performing_services', models.ManyToManyField(to='catalogs.OKMUService', verbose_name='Выполняемые услуги')),
            ],
            options={
                'verbose_name_plural': 'Специалисты',
                'verbose_name': 'Специалист',
            },
        ),
        migrations.AddField(
            model_name='cell',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Specialist', verbose_name='Специалист'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Department', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cell', verbose_name='Ячейка'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Patient', verbose_name='Пациент'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.OKMUService', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Specialist', verbose_name='Специалист'),
        ),
    ]
