# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-22 06:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Время')),
                ('level', models.CharField(db_index=True, max_length=256, verbose_name='Уровень')),
                ('logger_name', models.CharField(max_length=256, verbose_name='Логгер')),
                ('source_file', models.CharField(max_length=1024, verbose_name='Источник')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('session_key', models.CharField(blank=True, max_length=127, null=True, verbose_name='Ключ сессии')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Время')),
                ('session_key', models.CharField(blank=True, max_length=127, null=True, verbose_name='Ключ сессии')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='Пользователь')),
                ('patient_id', models.IntegerField(blank=True, null=True, verbose_name='ID Пациента')),
                ('action', models.CharField(max_length=255, verbose_name='Действие')),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Информация о действии')),
            ],
            options={
                'verbose_name': 'Дейсвие пользователя',
                'verbose_name_plural': 'Дейсвия пользователей',
            },
        ),
    ]
