# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 03:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdMatchingTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.IntegerField(verbose_name='ID сущности')),
                ('external_id', models.CharField(max_length=128, verbose_name='ID во внешней системе')),
            ],
            options={
                'verbose_name_plural': 'Таблица соответсвий id',
            },
        ),
        migrations.CreateModel(
            name='ObjectMatchingTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_name', models.CharField(max_length=128, verbose_name='Имя таблицы')),
                ('external_name', models.CharField(max_length=128, verbose_name='Имя во внешней системе')),
            ],
            options={
                'verbose_name_plural': 'Таблица соответсвий объектов ',
            },
        ),
        migrations.CreateModel(
            name='QmsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('connection_param', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Настройки соединения')),
                ('db_code', models.CharField(max_length=128, verbose_name='Код основной базы данных')),
                ('coding', models.CharField(max_length=16, verbose_name='Кодировка базы данных')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Clinic', verbose_name='Мед. учреждение')),
            ],
            options={
                'verbose_name_plural': 'Базы данных QMS',
                'verbose_name': 'База данных QMS',
            },
        ),
        migrations.AddField(
            model_name='idmatchingtable',
            name='object_matching_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qmsintegration.ObjectMatchingTable'),
        ),
        migrations.AlterUniqueTogether(
            name='idmatchingtable',
            unique_together=set([('internal_id', 'object_matching_table')]),
        ),
    ]
